[package]
name = "red_hot"
version = "0.1.0"
edition.workspace = true
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ash = { workspace = true }
ash-window = { workspace = true }
num = { workspace = true }
raw-window-handle = { workspace = true }
winit = { workspace = true }

[workspace]
members = ["examples/*"]

[workspace.package]
edition = "2021"

[workspace.dependencies]
ash = "0.38.0"
ash-window = "0.13.0"
glb = { git = "https://github.com/MBStarup/glb_rs", version = "0.1.0" }
num = "0.4.3"
rand = "0.10.2"
raw-window-handle = "0.6.2"
red_hot = { path = "." }
winit = "0.30.13"